### ISSUE TITLE
read data to datatable

### ISSUE THREAD

**Issue by FreeVB** [smourier/SheetReader#1]
Obtain whether the data in EXCEL can be converted to a datatable and then used as a data source for the datagridview.

**Comment by smourier** [comment]
Hi,

Is there a question here?

**Comment by FreeVB** [comment]
I don't know how to do it, how should I do it?

**Comment by smourier** [comment]
This https://github.com/smourier/SheetReader/blob/main/SheetReader.Test/Program.cs demonstrates how to enumerate all sheets, rows and cells, once you have that you can create what you want

**Comment by smourier** [comment]
closed due to inactivity
