### ISSUE TITLE
sort

### ISSUE THREAD

**Issue by FreeVB** [smourier/SheetReader#2]
Hello, how to achieve double-click or single-camera column header sorting.

**Comment by smourier** [comment]
Hi,

You can modify the code in SheetControl, for example here:

        protected override void OnPreviewMouseDoubleClick(MouseButtonEventArgs e)
        {
            if (e.LeftButton == MouseButtonState.Pressed)
            {
                var sheet = Sheet;
                if (sheet != null)
                {
                    var result = HitTest(e.GetPosition(_scrollViewer));
                    if (result.MovingColumnIndex.HasValue)
                    {
                        var next = Keyboard.Modifiers.HasFlag(ModifierKeys.Shift) && Keyboard.Modifiers.HasFlag(ModifierKeys.Control);
                        SetColumnsAutoSize(result.MovingColumnIndex.Value, next, sheet.Rows.Values);
                    }
                    else
                    {
                       // test double click here
                    }
                }
            }
        }


Then you'll have to reload the document.

But, since it's a good feature to add, I will do it myself in the next couple of days.

**Comment by FreeVB** [comment]
Thank you for your reply and look forward to updating the code.
Also, the current version column does not support drag-and-drop.

**Comment by smourier** [comment]
Sorting was added with this commit https://github.com/smourier/SheetReader/commit/191d8b9a863e4832976ff94ee2cce010bfa84bb8
