### ISSUE TITLE
Numeric sorting

### ISSUE THREAD

**Issue by FreeVB** [smourier/SheetReader#3]
Numeric sorting
I've added a few lines of code to the Compare method, which can be used to sort the numbers by their actual size, maybe you will have a better way to implement it, and I look forward to updating it in the new version.

```
protected virtual int Compare(BookDocumentCell? x, BookDocumentCell? y, Comparison<BookDocumentCell?>? comparison)
{
    if (comparison != null)
        return comparison(x, y);

    IComparable? ix = x?.Value as IComparable;
    IComparable? iy = y?.Value as IComparable;
    if (double.TryParse(x.Value.ToString(), out double valueX) && double.TryParse(y.Value.ToString(), out double valueY))
    {
        return valueX.CompareTo(valueY);
    }
 ...
}
```

**Comment by smourier** [comment]
This is too specific for me to be included in SheetReader, but you can do that programmatically using the `comparison` parameter, that's exactly why it's there for.
